name: Auto Fetch and Deploy

on:
  schedule:
    - cron: '0 */2 * * *' # 每 2 小时自动抓取并更新一次页面
  workflow_dispatch: # 支持手动点击运行

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Fetch Script
        run: node fetch.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-github-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
